<?php if($crumbs && is_array($crumbs)): ?>
<div class="container">
    <section class="breadcrumbs">
        <ul>
            <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                <li class="breadcrumbs--element <?php echo $_crumbName ?>">
                <?php if($_crumbInfo['link']): ?>
                    <a class="breadcrumbs--item" href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                <?php elseif($_crumbInfo['last']): ?>
                    <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
                <?php else: ?>
                    <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                <?php endif; ?>
                <?php if(!$_crumbInfo['last']): ?>
                    <span>/ </span>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <ul>
            <li class="breadcrumbs--element breadcrumbs--element-back">
                <a class="breadcrumbs--item" href="#">Back</a>
            </li>
        </ul>
    </section>
</div>
<?php endif; ?>
