<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div class="info--images selfImages">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <a href="#" class="selfImages--item" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(73); ?>" width="73" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
        </a>
    <?php endforeach; ?>
</div>
<div class="info--generalImage">
    <img src="<?=$this->helper('catalog/image')->init($_product, 'image')?>" alt="<?=$this->escapeHtml($this->getImageLabel())?>" title="<?=$this->escapeHtml($this->getImageLabel())?>" />
</div>
